[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/script"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/script.js"
  to = "/.netlify/functions/gateway"
  status = 200

[[redirects]]
  from = "/loader"
  to = "/.netlify/functions/gateway"
  status = 200

[[headers]]
  for = "/.netlify/functions/gateway"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"